Create error parser for sbt publish
To highlight this error relating to publishing:
java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled